#!/usr/bin/env bash
# Install PHP-FPM env vars for OSiris SMTP (nginx pool can send mail without reading secret files).
# Run on server: sudo bash scripts/install-php-fpm-mail-env.sh
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
API="$ROOT/public_html/api"
OUT="/etc/php-fpm.d/zz-osiris-mail.conf"

if [[ "$(id -u)" -ne 0 ]]; then
  echo "Run as root: sudo bash $0" >&2
  exit 1
fi

export PLATFORM_SMTP_PASS=""
# shellcheck source=/dev/null
[[ -f "$API/.platform-sso.env" ]] && set -a && source "$API/.platform-sso.env" && set +a
if [[ -f "$API/.platform-mail.secret" ]]; then
  while IFS= read -r line || [[ -n "$line" ]]; do
    [[ "$line" =~ ^PLATFORM_ ]] || continue
    key="${line%%=*}"
    val="${line#*=}"
    export "$key=$val"
  done < "$API/.platform-mail.secret"
fi

{
  echo "; OSiris platform mail — generated by install-php-fpm-mail-env.sh"
  echo "env[PLATFORM_MAIL_PROVIDER] = ${PLATFORM_MAIL_PROVIDER:-smtp}"
  echo "env[PLATFORM_MAIL_FROM] = ${PLATFORM_MAIL_FROM:-OSiris <noreply@guillaumelassiat.com>}"
  echo "env[PLATFORM_SMTP_HOST] = ${PLATFORM_SMTP_HOST:-smtp.ionos.fr}"
  echo "env[PLATFORM_SMTP_PORT] = ${PLATFORM_SMTP_PORT:-587}"
  echo "env[PLATFORM_SMTP_USER] = ${PLATFORM_SMTP_USER:-noreply@guillaumelassiat.com}"
  echo "env[PLATFORM_SMTP_TLS] = ${PLATFORM_SMTP_TLS:-starttls}"
  if [[ -n "${PLATFORM_SMTP_PASS:-}" ]]; then
    echo "env[PLATFORM_SMTP_PASS] = ${PLATFORM_SMTP_PASS}"
  fi
  if [[ -n "${PLATFORM_RESEND_API_KEY:-}" ]]; then
    echo "env[PLATFORM_RESEND_API_KEY] = ${PLATFORM_RESEND_API_KEY}"
  fi
} > "$OUT"
chmod 644 "$OUT"
chown root:root "$OUT"
echo "Wrote $OUT"
systemctl reload php-fpm 2>/dev/null || systemctl reload php-fpm.service 2>/dev/null || true
echo "Reloaded php-fpm. Test: php $ROOT/scripts/test-platform-mail.php your@email.com"
